### PR TITLE
Fixed spacing causing rendering issues

### PR DESCRIPTION
**Pull request by rlthompson904**

### CODE REVIEW

**Comment by hope77777** [comment]
"I'm experiencing the same issue as the pull request is there an ETA on when this will be reviewed/merged?"

**Comment by hope77777** [comment]
Classes currently running on this. Can it be pushed? Thanks

**Comment by hope77777** [comment]
Classes currently running on this. Can it be merged? Thanks

**Comment by ctesta-oneillmsft** [comment]
merged

**Pull request merged**
